services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: jackyoungdev/kafka-backend-api:0.1
    ports:
      - "5335:5335"
    env_file:
      - ./api/.env
    depends_on:
      - db
    networks:
      - kafka_dashboard

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: kafka_dashboard
      POSTGRES_USER: kafka_user
      POSTGRES_PASSWORD: kafka_password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./api/create_database.sql:/docker-entrypoint-initdb.d/create_database.sql
    networks:
      - kafka_dashboard

  kafka-broker:
    image: bitnami/kafka:3.7
    ports:
      - "9092:9092"
    environment:
      KAFKA_CFG_NODE_ID: 0
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafka-broker:9093
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka-broker:9092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CREATE_TOPICS: "stock-records:1:1"
    networks:
      - kafka_dashboard

  kafka-app:
    build:
      context: ./kafka
      dockerfile: Dockerfile
    image: jackyoungdev/backend-kafka:0.1
    depends_on:
      - kafka-broker
      - db
    networks:
      - kafka_dashboard

networks:
  kafka_dashboard:
    external: true
volumes:
  pgdata:
